# ref: https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions
name: Maven Version Bump Action
description: A simple GitHub Actions to bump the version of Maven projects

author: Nick Nichols

branding:
  color: purple
  icon: git-commit

inputs:
  github-token:
    description: 'A GitHub auth token to be able to create the pull request'
    required: true
  pom-path:
    description: 'The relative location of your pom.xml file'
    required: true
    default: '.'
  git-email:
    description: 'The email address used to create the version bump commit with.'
    required: true
    default: 41898282+github-actions[bot]@users.noreply.github.com
  git-username:
    description: 'The name to use for the version bump commit. e.g. github.actor'
    required: true
    default: github-actions[bot]

runs:
  using: docker
  image: Dockerfile
  env:
    TOKEN: ${{ inputs.github-token }}
    EMAIL: ${{ inputs.git-email }}
    NAME: ${{ inputs.git-username }}
    POMPATH: ${{ inputs.pom-path}}
